### PR TITLE
Adding the german language

### PR DESCRIPTION
**Pull request by max312**
This may need some fixing on the page itself, as some german sentences are really long.
It also contains umlauts which may cause trouble in non Unicode environments.

### CODE REVIEW

**Comment by max312** [comment]
Before i forget it: Thank you for this project, I appreciate your work!

**Comment by Ishou** [comment]
Thanks for your contribution 🤩🤩

Could you please bump the version in the package.json file and also tell me how you'd like to be mentioned in the CONTRIBUTORS.md file? (otherwise you can add it yourself, just put your language in alphabetical order, so just after French for German)

**Comment by max312** [comment]
Done!
Sorry for those many commits coming in bit by bit, my workflow autocommits to remote 🙈

**Comment by Ishou** [comment]
Thanks for fixing the order in the contributors list, it's just to keep things neutral, otherwise it'd be like we put a language higher than another one

No problem for the commits I'll squash & merge ;), could you just fix the indent in package.json and keep it to two spaces please, then everything'd perfect!

**Review by Ishou — CHANGES_REQUESTED** [review]
You missed 4 lines 😛

**Comment by max312** [comment]
Should be done now ^^
My VS Code is a little bit too concerned with 4 spaces

**Review by Ishou — APPROVED** [review]
Perfect ❤️  thanks again for your contribution! 😄
Tell me if you join our Discord I'll add you the @Contributor role

**Comment by max312** [comment]
> Perfect ❤️ thanks again for your contribution! 😄
> Tell me if you join our Discord I'll add you the @contributor role

Just texted u there ;-)

**Pull request merged**
